name = "vrp-system-v4"
compatibility_date = "2024-07-01"

[env.production]
route = "vrp-system.your-domain.com/*"

[env.staging]
route = "staging-vrp-system.your-domain.com/*"

[[pages_build_output_dir]]
# Build configuration for Cloudflare Pages